# Generated by Django 4.1.7 on 2023-04-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_toggleswitch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToggleSwitch',
        ),
        migrations.AddField(
            model_name='register',
            name='is_on',
            field=models.BooleanField(default=False),
        ),
    ]
